### ISSUE TITLE
Steps remaining before formally announcing Guides

### ISSUE THREAD

**Issue by QuincyLarson** [freeCodeCamp/guides#145]
Here is a checklist of things I propose we do before announcing guides:
- [x] Remove the articles directory #147 PR #242 
- [x] Create a good index.md file for the root article directory (that shows when you navigate to Guides directly, this should be situated in `src/pages/` #148 
- [x] Make sure search works properly
- [x] Set up a redirect in NGINX to guide.freecodecamp.org to guide.netlify.com 
- [x] HTTPS
- [x] Ad a new Google Analytics code #248

- [ ] QA and merge all existing articles submissions (to minimize merge conflicts when I recategorize articles)
- [ ] Create a 0.1.0 GitHub release
- [x] Recategorize some of the loose articles into more descriptive subfolders.
- [ ] Write a Medium article announcing Guides and explaining what it does (I will do this)

Date of announcement: Wednesday, September 20

**Comment by Bouncey** [comment]
>  Recategorize some of the loose articles into more descriptive subfolders.

We can expand on this and remove the `articles` dir. That way, we will have URLs like `freecodecamp.org/guide/<some-category>/<some-article>`, removing the `articles` path level.

For this to be accomplished, `_normaliseAriticles` and `createNavData` will need to be refactored to remove the dependency on the `articles` dir.

**Comment by QuincyLarson** [comment]
@Bouncey I seem to recall @BerkeleyTrue saying there's no need to remove the `articles` directory, and that we can just mount that directory in NGINX or in Netlfy itself.

**Comment by nsuchy** [comment]
Is using a subdomain like guides.freecodecamp.org possible with Netlfy?

**Comment by QuincyLarson** [comment]
@nsuchy We'd rather use a subdirectory. It's better for SEO.

**Comment by Bouncey** [comment]
@QuincyLarson All the relative urls point to `/articles/some-cat/some-article` so the slug would end up being `guide/articles/some-cat/some-article`

**Comment by QuincyLarson** [comment]
@Bouncey OK - we'll see what @BerkeleyTrue can do with it once we launch. We don't want the /articles/ in there because it will lengthen the URL.

**Comment by systimotic** [comment]
I'm not sure if having the `hint` buttons link to the guides is a good idea. They require some work to get up to par with the forum. Example: http://guide.freecodecamp.org/articles/certificates/dna-pairing/

**Comment by QuincyLarson** [comment]
@systimotic Yes - we have more we need to do to get the guide articles ready. We can do this after we ship if necessary. We don't need to hold up the release of guides for this. I've removed this item from my bulletpoint list above.

**Comment by QuincyLarson** [comment]
All right, we are going to launch this into the world. Friday's [Mail for Good launch was well received](https://twitter.com/ossia/status/909417221352386561), and my hope is that Guides will get a similar welcome.

I've updated the to-do checklist. I'll handle the topic re-organization and the Medium article.

@systimotic and @HKuz can you take a look at the outstanding article pull requests, QA them and merge them?

@Bouncey can you create a formal 0.1.0 release on GitHub?

My plan is to have the article ready for Wednesday morning and to add Guide to the NavBar, and to announce the guide as the central article of my Thursday email blast.

**Comment by HKuz** [comment]
Sounds great! I just went through the open PRs and merged what I could. Anything content-based that's still open all have comments/changes/rebasing that need to be addressed. I just opened a PR, too, (sorry for adding to the pile) that does some README cleanup.
